// AUTO-GENERATED by npm run build:registry — do not edit manually.
// Source of truth: src/registry/sites.ts
// Rebuild with: npm run build:ext
const REGISTRY_HOSTNAMES = ["cos.com","ralphlauren.com","bananarepublic.gap.com","buckmason.com","jcrew.com"];
