/* Copyright 2015-2026 Quantum Metric, Inc. All rights reserved. For US patents see https://www.quantummetric.com/legal/patents/. For EULA see https://www.quantummetric.com/legal/eula. 1.35.36 86b1a1a103c133c73bb4660c32468c7a089e54a8 */
(function() {
var setInterval = window['__zone_symbol__setInterval'] || window.setInterval;
var clearInterval = window['__zone_symbol__clearInterval'] || window.clearInterval;
var setTimeout = window['__zone_symbol__setTimeout'] || window.setTimeout;
var console = window['console'];
var clearTimeout = window['__zone_symbol__clearTimeout'] || window.clearTimeout;
var MutationObserver = window['__zone_symbol__MutationObserver'] || window.MutationObserver;
var queueMicrotask = window['__zone_symbol__queueMicrotask'] || window.queueMicrotask;
var Promise = window['__zone_symbol__Promise'] || window.Promise; function u(a){a.h||(window.fetch=function(b,c){const g=(new Date).getTime();let h,k=null,e=null,p=null;try{if(h=b instanceof Request?b:new Request(b,c),typeof b==="string")typeof c==="object"?(e=c.body,k=c.method,p=y(h.headers)):k="GET";else if(typeof b==="object"&&b.constructor&&b.constructor.name==="Request"&&typeof b.clone==="function"){k=c&&c.method||b.method;var f=b.clone();c&&c.body&&typeof c.body=="string"&&c.body.length?e=c.body:window.ReadableStream&&f.body instanceof window.ReadableStream?
z(f.body).then(m=>e=m):f.text().then(function(m){e=m});p=y(c&&c.headers||f.headers)}}catch(m){}let n=!1,l=!1,d=!1,q,r=c&&c.signal&&c.signal instanceof AbortSignal;try{r&&(q=new AbortController,c.signal.addEventListener("abort",function(){l=!0;v()}),c.signal=q.signal)}catch(m){}let w=!1;const v=()=>{w||!l||n&&!d||(q.abort(),w=!0)};a.m();f=a.l.apply(this,arguments);try{f.then(function(m){try{a.o&&(n=!0),m.qmre_f||(m.qmre_f=1,A(a,m.clone(),k,e,g,p).finally(()=>{d=!0;v()}))}catch(t){}r&&["arrayBuffer",
"blob","formData","json","text"].forEach((t=>x=>{const C=t[x];t[x]=function(){n=!0;return C.call(this,arguments)}})(m));return m}).catch(m=>{m.name==="AbortError"&&h&&(m={response:"",getAllResponseHeaders:function(){return""}},p&&(m.u=p),m.response=a.i,a.g({type:a.type,args:[-1,h.url,g,k,e,m]}))})}catch(m){}return f},a.h=!0)}
function y(a){var b="";try{if(a)if(b="",typeof a.entries=="function"){const c=a.entries();let g=c.next();for(a=0;!g.done&&a<1E3;)b+=`${g.value[0]}: ${g.value[1]}\r\n`,g=c.next(),a++}else for(let c in a)a.hasOwnProperty(c)&&(b+=`${c}: ${a.get?a.get(c):a[c]}\r\n`)}catch(c){}return b}
function A(a,b,c="",g=null,h=0,k=null){return new Promise((e,p)=>{try{if(typeof b=="object"&&b.constructor&&b.constructor.name==="Response"&&!b.j){let f={response:"",qend:(new Date).getTime(),getAllResponseHeaders:function(){let n="";if(b.headers&&typeof b.headers.entries=="function"){const l=b.headers.entries();let d=0,q=l.next();for(;!q.done&&d<1E3;)n+=`${q.value[0]}: ${q.value[1]}\r\n`,q=l.next(),d++}return n}};k&&(f.reqHeaders=k);if(b.text&&typeof b.clone==="function"){const n=b.clone();n.text().then(function(l){f.response=
l;a.g({type:a.type,args:[n.status,n.url,h,c,g,f]})}).catch(l=>{l.name==="AbortError"&&(f.response=a.i,a.g({type:a.type,args:[n.status,n.url,h,c,g,f]}))}).finally(e)}b.j=1}}catch(f){p(f)}})}async function z(a){let b="";const c=window.TextDecoder&&new window.TextDecoder;try{const g=a.getReader();for(;;){const {value:h,done:k}=await g.read();if(k)break;a="";if(c)a=c.decode(h);else for(let e=0;e<h.length;e++)a+=String.fromCharCode(parseInt(h[e],10));b+=a}}catch(g){}return b}
class B{constructor(a,b,c){this.type="fetch";this.h=!1;a&&b&&c?(this.l=a,this.g=b,this.m=c,this.i="QM: fetch aborted.",this.o=!1,u(this)):console.warn("Unable to setup QM: Fetch Interceptor")}};function D(a){function b(l,d){try{var q=E(k,this);q.method=l;q.url=d}catch(r){}return e.apply(this,arguments)}function c(l){var d=this;try{d.addEventListener("abort",function(){d.qaborted=!0},!1),d.addEventListener("error",function(){d.qnetworkError=!0},!1),d.addEventListener("timeout",function(){d.qnetworkError=!0;d.qtimedOut=!0},!1),setTimeout(function(){F(k,d,l)},0)}catch(q){}return p.apply(this,arguments)}function g(l,d){try{this.reqHeaders=(this.reqHeaders||"")+(l+": "+d+"\r\n")}catch(q){}return f.apply(this,
arguments)}function h(){try{this.qaborted=!0}catch(l){}return n.apply(this,arguments)}const k=a;a=k.i.prototype;var e=a.open,p=a.send,f=a.setRequestHeader,n=a.abort;if(e&&p&&f&&(a.open=b,a.send=c,a.setRequestHeader=g,a.abort=h,a.open!=b))try{Object.defineProperty(a,"open",{value:b,writable:!0,enumerable:!0,configurable:!0}),Object.defineProperty(a,"send",{value:c,writable:!0,enumerable:!0,configurable:!0}),Object.defineProperty(a,"setRequestHeader",{value:g,writable:!0,enumerable:!0,configurable:!0}),
Object.defineProperty(a,"abort",{value:h,writable:!0,enumerable:!0,configurable:!0})}catch(l){}}function E(a,b){a.data.has(b)||a.data.set(b,{});return a.data.get(b)}
function F(a,b,c){var g=E(a,b),h=g.url,k=g.method,e=(new Date).getTime();a.h();if(b.readyState===4)b.qend=(new Date).getTime(),a.g({type:"xhr",args:[b.status,h,e,k,c,b]});else{var p=function(){try{h=h||b.responseURL,b.readyState==4&&(b.qend=(new Date).getTime(),b.qresponse=b.response,a.g({type:"xhr",args:[b.status,h,e,k,c,b]}),b.removeEventListener&&b.removeEventListener("readystatechange",p))}catch(f){}};b.addEventListener&&b.addEventListener("readystatechange",p,!1)}}
class G{constructor(a,b,c){a&&b&&c?(this.i=a,this.g=b,this.h=c,this.data=new window.WeakMap,D(this)):console.warn("Unable to setup QM: XHR Interceptor")}};(function(a){function b(){f&&f()}function c(d){p&&e.length<l.maxCacheEntries&&e.push(d);for(const q of n)q.call(this,d)}function g(){a.setTimeout(()=>{p=!1;e=[]},l.maxCacheRecordingWindow)}let h=a._o_Fetch||a.fetch,k=a.XMLHttpRequest,e=[],p=!0,f=null;const n=[];let l=Object.assign({maxCacheEntries:200,maxCacheRecordingWindow:15E3},a.QuantumMetricNetworkInterceptorConfig||{});window.QuantumMetricNetworkInterceptor||(window.QuantumMetricNetworkInterceptor={getRootFetch:()=>h,getRootXHR:()=>k,getEntries:()=>
e,preRequest:d=>{f=d},onAPI:d=>{n.push(d)}});new B(h,c,b);new G(k,c,b);document.visibilityState==="visible"?g():document.addEventListener("visibilitychange",()=>{document.visibilityState==="visible"&&g()},{once:!0})})(window);})();

