//tealium universal tag - utag.527 ut4.0.202604090403, Copyright 2026 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={"id":id};utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}
var match=/ut\d\.(\d*)\..*/.exec(utag.cfg.v);if(utag.ut.loader===undefined||!match||parseInt(match[1])<41){u.loader=function(o,a,b,c,l,m){utag.DB(o);a=document;if(o.type=="iframe"){m=a.getElementById(o.id);if(m&&m.tagName=="IFRAME"){b=m;}else{b=a.createElement("iframe");}o.attrs=o.attrs||{};utag.ut.merge(o.attrs,{"height":"1","width":"1","style":"display:none"},0);}else if(o.type=="img"){utag.DB("Attach img: "+o.src);b=new Image();}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";}if(o.id){b.id=o.id;}for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute("src",o.src);if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState=="complete"||this.readyState=="loaded"){this.onreadystatechange=null;o.cb();}};}}if(o.type!="img"&&!m){l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}}};}else{u.loader=utag.ut.loader;}
if(utag.ut.typeOf===undefined){u.typeOf=function(e){return({}).toString.call(e).match(/\s([a-zA-Z]+)/)[1].toLowerCase();};}else{u.typeOf=utag.ut.typeOf;}
u.ev={"view":1,"link":1};u.hasgtagjs=function(){window.gtagRename=window.gtagRename||""||"gtag";if(utag.ut.gtagScriptRequested){return true;}
var i,s=document.getElementsByTagName("script");for(i=0;i<s.length;i++){if(s[i].src&&s[i].src.indexOf("gtag/js")>=0){return true;}}
window.dataLayer=window.dataLayer||[];if(typeof window[window.gtagRename]!=="function"){window[window.gtagRename]=function(){dataLayer.push(arguments);};window[window.gtagRename]("js",new Date());}
return false;};u.scriptrequested=u.hasgtagjs();u.o=window[window.gtagRename];u.map_func=function(arr,obj,item){var i=arr.shift();obj[i]=obj[i]||{};if(arr.length>0){u.map_func(arr,obj[i],item);}else{obj[i]=item;}};u.hasOwn=function(o,a){return o!=null&&Object.prototype.hasOwnProperty.call(o,a);};u.isEmptyObject=function(o,a){for(a in o){if(u.hasOwn(o,a)){return false;}}return true;};u.map={"gtag_account_id":"advertiser_id","gtag_activity_group":"activity_group","gtag_activity_id":"activity","gtag_counting_method":"counting_method","gtag_event":"event","ap_value":"custom.u1","qp.cid":"custom.u4,custom.u5","checkout_brand":"custom.u6","last_tid":"custom.u7","order_id":"custom.u9","order_net_demand":"custom.u10,order_total","order_shipping":"custom.u12","order_tax":"custom.u13","page_name":"custom.u14","page_type":"custom.u15","dom.url":"custom.u16","product_id":"custom.u17","customer_billing_zip":"custom.u19","customer_shipping_zip":"custom.u20","cart_gross_merchandise":"custom.u3","product_line_and_brand_discount":"custom.u11","bopis_order_type":"custom.u21","at_is_new_customer_flag":"custom.u8","br_is_new_customer_flag":"custom.u22","gap_is_new_customer_flag":"custom.u24","on_is_new_customer_flag":"custom.u26","mtl_clicks":"custom.u27","tealium_random":"dc_custom_params.match_id,dc_custom_params.ord"};u.extend=[function(a,b){try{if(1){b.gtag_account_id="stop";b.gtag_activity_group="stop";b.gtag_activity_id="stop";b.gtag_counting_method="stop";b.gtag_event="stop";if(b.business_unit_id){let c=["standard","transactions","unique"];let e=["conversion","purchase"];let p=["Home","Division","Category","Product","ShoppingBag","Search","OrderConfirmation","MiniBag"];let m=b['minibag_type'];let cid=b['qp.cid'];let page=b['page_type'];let tag={};let pmg1='DC-6900831';let pmg2='DC-8030980';let phd='DC-10709046';let buid=parseInt(b.business_unit_id);switch(buid){case 1:let akqa='DC-1956281';tag={acct:[pmg1,pmg2,akqa],group:['gap_r0','usgap0','gapde0'],activity:['gap_r0','gap-u002','gapde0'],count:[c[0],c[0],c[2]],event:[e[0]]};var addSinglePHD=(activity_id)=>{tag.acct=tag.acct.concat([phd]);tag.group=tag.group.concat(['phdga0']);tag.activity=tag.activity.concat([activity_id]);tag.count=tag.count.concat([c[0]]);};if(page){if(page===p[0]||page===p[2]||page===p[3]||page===p[4]||page===p[5]||(page===p[8]&&m==='shoppingBag')){tag.acct=tag.acct.concat([pmg2,akqa,akqa]);tag.group=tag.group.concat(['usgap0','gapde0','gapde0']);tag.count=tag.count.concat([c[0],c[2],c[0]]);if(page===p[0]){tag.acct=tag.acct.concat([akqa,phd]);tag.group=tag.group.concat(['gapco366','phdga0']);tag.count=tag.count.concat([c[0],c[0]]);tag.activity=tag.activity.concat(['gap-u0','gapde00','gapde000','gapcu255','gapho0']);}else if(page===p[2]||page===p[5]){tag.activity=tag.activity.concat(['gap-u000','gapde00','gapde000']);if(page===p[2]){if(cid==="1151802"){addSinglePHD('gapgi00');}
if(cid==="11900"){addSinglePHD('angus0');}
if(cid==="1027221"){addSinglePHD('gapba0');}
if(cid==="5664"){addSinglePHD('women00');}
if(cid==="1189735"){addSinglePHD('gapal0');}}}else if(page===p[3]){tag.activity=tag.activity.concat(['gap-u001','gapde00','gapde000']);}else if(page===p[4]||(page===p[8]&&m==='shoppingBag')){tag.acct=tag.acct.concat([akqa,akqa]);tag.group=tag.group.concat(['gapco366','gapde0']);tag.activity=tag.activity.concat(['gap-u00','gapde00','gapde000','gapco303','gapde001']);tag.count=tag.count.concat([c[0],c[2]]);}}else if(page===p[1]){if(cid==="1182426"){addSinglePHD('gapte0');}}else if(page===p[6]){tag.acct=[pmg1,pmg2,akqa,akqa,akqa];tag.group=['gap_p0','usgap00','gapco366','gapco366','gapde0'];tag.activity=['gap_p0','gap-u0','gapco840','gapco087','gapde002'];tag.count=[c[1],c[1],c[1],c[1],c[1]];tag.event=[e[1]];}else if(cid==="1174646"){addSinglePHD('gapio0');}else if(cid==="1182991"){addSinglePHD('gapco0');}}
break;case 2:pmg2='DC-8121544';phd='DC-1528929';tag={acct:[pmg1,pmg2,phd,phd],group:['gap_r0','usgap0','brcom299','brcom299'],activity:['gap_r0','banan0','brbro937','brsal434'],count:[c[0],c[0],c[0],c[0]],event:[e[0]]}
if(page){if(page===p[0]||page===p[2]||page===p[3]){tag.acct=tag.acct.concat([pmg2,phd]);tag.group=tag.group.concat(['usgap0','brcom299']);tag.count=tag.count.concat([c[0],c[0]]);b.gtag_account_id=[pmg2,phd];b.gtag_activity_group=['usgap0','brcom299'];b.gtag_counting_method=['standard','standard'];if(page===p[0]){tag.activity=tag.activity.concat(['banan00','brows891']);}else if(page===p[2]){tag.activity=tag.activity.concat(['banan000','brows891']);}else if(page===p[3]){tag.activity=tag.activity.concat(['banan001','brows891']);}}else if(page===p[1]){tag.acct=tag.acct.concat([phd]);tag.group=tag.group.concat(['brcom299']);tag.activity=tag.activity.concat(['brows891']);tag.count=tag.count.concat([c[0]]);}else if(page==p[4]||(page===p[8]&&m==='shoppingBag')){tag.acct=tag.acct.concat([pmg2,phd]);tag.group=tag.group.concat(['usgap0','brcom299']);tag.activity=tag.activity.concat(['banan002','brcar279']);tag.count=tag.count.concat([c[0],c[2]]);}else if(page==p[6]){tag.acct=[pmg1,pmg2,phd];tag.group=['gap_p0','us_ga0','brcom299'];tag.activity=['gap_p0','banan0','brord742'];tag.count=[c[1],c[1],c[1]];tag.event=[e[1]];}}
break;case 3:pmg2='DC-8110008';phd='DC-1393326';tag={acct:[pmg1,pmg2,phd,phd],group:['gap_r0','usold0','conve759','conve759'],activity:['gap_r0','oldna001','oldna970','OldNa0'],count:[c[0],c[0],c[0],c[2]],event:[e[0]]}
if(page){if(page===p[0]||page===p[2]||page===p[3]||page===p[4]||(page===p[8]&&m==='shoppingBag')){tag.acct=tag.acct.concat([pmg2]);tag.group=tag.group.concat(['usold0']);tag.count=tag.count.concat([c[0]]);if(page===p[0]){tag.activity=tag.activity.concat(['oldna0']);}else if(page===p[2]){tag.activity=tag.activity.concat(['oldna00']);}else if(page===p[3]){tag.activity=tag.activity.concat(['oldna000']);}else if(page===p[4]||(page===p[8]&&m==='shoppingBag')){tag.acct=tag.acct.concat([phd]);tag.group=tag.group.concat(['conve759']);tag.count=tag.count.concat([c[2]]);tag.activity=tag.activity.concat(['oldna002','oldna919']);}}else if(page===p[6]){tag.acct=[pmg1,pmg2,phd,phd,phd];tag.group=['gap_p0','usold00','conve759','oldna0','conve759'];tag.activity=['gap_p0','oldna0','oldna914','oldna0','oldna970'];tag.count=[c[1],c[1],c[0],c[2],c[0]];tag.event=[e[1]];}else if(cid==="1095422"){tag.acct=tag.acct.concat([pmg2]);tag.group=tag.group.concat(['usold0']);tag.activity=tag.activity.concat(['oldna00q']);tag.count=tag.count.concat([c[0]]);}}
break;case 10:pmg2='DC-8114858';phd='DC-3785825';tag={acct:[pmg1,pmg2,phd],group:['gap_r0','usath0','athle049'],activity:['gap_r0','athle0','athle432'],count:[c[0],c[0],c[0]],event:[e[0]]}
if(page){if(page===p[0]||page===p[2]||page===p[3]||page===p[4]||(page===p[8]&&m==='shoppingBag')){tag.acct=tag.acct.concat([pmg2]);tag.group=tag.group.concat(['usath0']);tag.count=tag.count.concat([c[0]]);if(page===p[0]){tag.activity=tag.activity.concat(['athle001']);}else if(page===p[2]){tag.activity=tag.activity.concat(['athle000']);}else if(page===p[3]){tag.activity=tag.activity.concat(['athle002']);}else if(page===p[4]||(page===p[8]&&m==='shoppingBag')){tag.acct=tag.acct.concat([phd]);tag.group=tag.group.concat(['athle049']);tag.count=tag.count.concat([c[2]]);tag.activity=tag.activity.concat(['athle00','athle816']);}}else if(page===p[6]){tag.group=['gap_p0','usath000','athle049'];tag.activity=['gap_p0','athle0','athle483'];tag.count=[c[1],c[1],c[0]];tag.event=[e[1]];}}
break;}
b.gtag_account_id=tag.acct;b.gtag_activity_group=tag.group;b.gtag_activity_id=tag.activity;b.gtag_counting_method=tag.count;b.gtag_event=tag.event;}}}catch(e){utag.DB(e)}}];u.callBack=function(){utag.ut.gtagScriptRequested=true;window.addEventListener('load',(event)=>{console.log('page is fully loaded');var floods=document.querySelectorAll('iframe[src*="fls.doubleclick"]');if(floods.length===0){console.info('No Google Floodlight Tags Loaded')}else{console.info('Parse Google Floodlight Tags');}
for(let flood of floods){if(flood.hasAttribute('title')===false){flood.setAttribute('title','Google Floodlight Tag');console.info(flood);}}});};u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){utag.DB("send:527");utag.DB(b);var d,e,f,h,i,j,_event,p,key;u.data={"qsp_delim":"&","kvp_delim":"=","base_url":"https://www.googletagmanager.com/gtag/js","advertiser_id":"","activity_group":"","activity":"","counting_method":"","custom_scripts":"true","session_id":"","product_quantity":[],"dc_custom_params":{},"event_name":"","event":[],"custom":{}};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};utag.DB("send:527:EXTENSIONS");utag.DB(b);for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.map_func(e[f].split("."),u.data,b[d]);}}else{h=d.split(":");if(h.length===2&&b[h[0]]===h[1]){if(u.map[d]){u.data.event=u.data.event.concat(u.map[d].split(","));}}}}
utag.DB("send:527:MAPPINGS");utag.DB(u.data);u.data.order_id=u.data.order_id||b._corder||"";u.data.order_total=u.data.order_total||b._ctotal||"";if(u.data.product_quantity.length===0&&b._cquan!==undefined){u.data.product_quantity=b._cquan.slice(0);}
if(typeof(u.data.advertiser_id)==="string"){u.data.advertiser_id=u.data.advertiser_id.split(",");}
if(typeof(u.data.activity_group)==="string"){u.data.activity_group=u.data.activity_group.split(",");}
if(typeof(u.data.activity)==="string"){u.data.activity=u.data.activity.split(",");}
if(typeof(u.data.counting_method)==="string"){u.data.counting_method=u.data.counting_method.split(",");}
if(typeof(u.data.session_id)==="string"){u.data.session_id=u.data.session_id.split(",");}
if(!u.data.advertiser_id){utag.DB(u.id+": Tag not fired: Required attribute not populated");return;}
u.data.base_url+="?id="+(u.data.advertiser_id[0]);for(i=0;i<u.data.advertiser_id.length;i++){u.o("config",u.data.advertiser_id[i]);}
if(u.data.order_id){for(i=0;i<u.data.event.length;i++){if(u.data.event[i]==="purchase"){p=true;}}
if(!p){u.data.event.push("purchase");}}
var total_qty=1;if(typeof(u.data.product_quantity)==="number"){total_qty=u.data.product_quantity;}else if(u.data.product_quantity.length===1){total_qty=u.data.product_quantity[0];}else if(u.data.product_quantity.length>1){for(i=0;i<u.data.product_quantity.length;i++){total_qty+=parseInt(u.data.product_quantity[i],10);}}
for(i=0;i<u.data.event.length;i++){_event=u.data.event[i];for(j=0;j<u.data.advertiser_id.length;j++){var eventIdData={};if(u.data.custom_scripts==="true"||u.data.custom_scripts){eventIdData.allow_custom_scripts=true;}else if(u.data.custom_scripts==="false"||!u.data.custom_scripts){eventIdData.allow_custom_scripts=false;}
if(u.data.session_id.length===1&&u.data.session_id[0]!==""){eventIdData.session_id=u.data.session_id[0];}else if(u.data.session_id[j]!==""){eventIdData.session_id=u.data.session_id[j];}
if(u.data.order_total){eventIdData.value=u.data.order_total;eventIdData.transaction_id=u.data.order_id;}
if(u.data.product_quantity){eventIdData.quantity=total_qty;}
for(key in u.data.custom){eventIdData[key]=u.data.custom[key];}
if(!u.isEmptyObject(u.data.dc_custom_params)){eventIdData.dc_custom_params={};for(key in u.data.dc_custom_params){eventIdData.dc_custom_params[key]=u.data.dc_custom_params[key];}}
eventIdData.send_to=u.data.advertiser_id[j]+"/"+u.data.activity_group[j]+"/"+u.data.activity[j]+"+"+u.data.counting_method[j];if(_event==="purchase"){u.o("event","purchase",eventIdData);}
if(_event==="conversion"){u.o("event","conversion",eventIdData);}}}
if(!u.hasgtagjs()){u.scriptrequested=true;u.loader({"type":"script","src":u.data.base_url,"cb":u.callBack,"loc":"script","id":"utag_527","attrs":{}});}
utag.DB("send:527:COMPLETE");}};utag.o[loader].loader.LOAD(id);}("527","gapinc.usgap"));}catch(error){utag.DB(error);}
