//tealium universal tag - utag.1317 ut4.0.202604090403, Copyright 2026 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}
if(utag.ut.loader===undefined){u.loader=function(o){var b,c,l,a=document;if(o.type==="iframe"){b=a.createElement("iframe");o.attrs=o.attrs||{"height":"1","width":"1","style":"display:none"};for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute("src",o.src);}else if(o.type=="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";for(l in utag.loader.GV(o.attrs)){b[l]=o.attrs[l];}b.src=o.src;}if(o.id){b.id=o.id};if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb()},false);}else{b.onreadystatechange=function(){if(this.readyState=='complete'||this.readyState=='loaded'){this.onreadystatechange=null;o.cb()}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b)}}}}else{u.loader=utag.ut.loader;}
u.ev={view:1};u.initialized=false;u.map={"order_id":"order_id","order_net_demand":"order_net_demand","product_cc_id":"product_cc_id","product_quantity":"product_quantity","product_sku":"product_sku","customer_blank_uuid":"customer_blank_uuid","product_brand":"product_brand","product_net_demand":"product_net_demand","abseg_cookie":"abseg_cookie","cnstrc_id":"cnstrc_id","cnstrc_purchase_data":"cnstrc_purchase_data","cnstrc_cells":"cnstrc_cells","product_id":"product_id"};u.extend=[];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={"base_url":"//cnstrc.com/js/cust/gap_nf8JL7.js"};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
if(u.data.customer_blank_uuid){window.cnstrcUserId=u.data.customer_blank_uuid;}
let cnstrCookie=u.data.abseg_cookie;if(cnstrCookie){window.testCells={};var cnstrSegNum='218-';var cnstrSeg={'gap':{'label':'gap'},'br':{'label':'bananaRepublic'},'at':{'label':'athleta'},'on':{'label':'oldNavy'},'gapfs':{'label':'gapFS'},'brfs':{'label':'bananaRepublicFS'}};var cnstrSegArray=Object.keys(cnstrSeg);for(var i=0;i<cnstrSegArray.length;i++){let seg=cnstrSegArray[i]+cnstrSegNum;if(cnstrCookie.indexOf(seg)>-1){let pos=cnstrCookie.indexOf(seg)+seg.length;let char=cnstrCookie.charAt(pos);let label=cnstrSeg[cnstrSegArray[i]].label;if(char==='a'){window.testCells[label]={'constructorio':'constructor'};}else if(char==='x'){window.testCells[label]={'constructorio':'control'}}}}}
if(u.data.order_id){window.cnstrcPurchaseData={};var items=[];if(u.data.product_cc_id&&u.data.product_cc_id.length>0){for(var i=0;i<u.data.product_cc_id.length;i++){items.push({item_id:u.data.product_id[i],variation_id:u.data.product_cc_id[i],sku_id:u.data.product_sku[i],price:parseFloat(u.data.product_net_demand[i]),count:u.data.product_quantity[i],brand:u.data.product_brand[i],});}
window.cnstrcPurchaseData={items:items,order_id:u.data.order_id,revenue:parseFloat(u.data.order_net_demand)};}}
if(!u.initialized){u.loader({"type":"script","src":u.data.base_url,"loc":"script","id":'utag_1317'});}
}};utag.o[loader].loader.LOAD(id);})("1317","gapinc.usgap");}catch(error){utag.DB(error);}
