//tealium universal tag - utag.811 ut4.0.202604090403, Copyright 2026 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={'view':1};u.initialized=false;u.map={"snapchat_id":"pixel_id","currency_code":"currency","order_net_demand":"price","order_id":"transaction_id","product_quantity":"number_items","product_sku":"item_ids","product_id":"item_category","hashed_customer_email":"user_hashed_email","bopis_order_type":"bopis_order_type","vendor_id":"client_dedup_id"};u.extend=[function(a,b){try{if(1){b.vendor_id=b.unknown_shopper_id+(Date.now()).toString().substr(0,9);}}catch(e){utag.DB(e)}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={"base_url":"//sc-static.net/scevent.min.js"
};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
(function(win,doc,sdk_url){if(win.snaptr)return;var tr=win.snaptr=function(){tr.handleRequest?tr.handleRequest.apply(tr,arguments):tr.queue.push(arguments);};tr.queue=[];var s='script';var new_script_section=doc.createElement(s);new_script_section.async=!0;new_script_section.src=sdk_url;var insert_pos=doc.getElementsByTagName(s)[0];insert_pos.parentNode.insertBefore(new_script_section,insert_pos);})(window,document,u.data.base_url);snaptr('init',u.data.pixel_id,{'user_hashed_email':u.data.user_hashed_email});if(u.data.item_ids){snaptr('track','PAGE_VIEW',{'client_dedup_id':u.data.client_dedup_id+'pv','item_ids':u.data.item_ids,'item_category':u.data.item_category});}else{snaptr('track','PAGE_VIEW');}
if(b.page_type){if(b.page_type==='OrderConfirmation'){snaptr('track','PURCHASE',{'client_dedup_id':u.data.client_dedup_id+'pur','currency':u.data.currency,'price':u.data.price,'transaction_id':u.data.transaction_id,'item_ids':u.data.item_ids,'item_category':u.data.item_category});snaptr('track','CUSTOM_EVENT_1',{'client_dedup_id':u.data.client_dedup_id+'ev1','description':u.data.bopis_order_type});}
if(b.page_type==='InlineBagAdd'||b.page_type==='QuickAdd'){snaptr('track','ADD_CART',{'client_dedup_id':u.data.client_dedup_id+'cart','number_items':u.data.number_items,'item_ids':u.data.item_ids,'item_category':u.data.item_category});}
if(b.page_type==='Product'||b.page_type==='QuickAddStart'){snaptr('track','VIEW_CONTENT',{'client_dedup_id':u.data.client_dedup_id+'vc','item_ids':u.data.item_ids,'item_category':u.data.item_category});}}
}};utag.o[loader].loader.LOAD(id);})("811","gapinc.usgap");}catch(error){utag.DB(error);}
