//tealium universal tag - utag.1004 ut4.0.202604090403, Copyright 2026 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={'view':1,'link':1};u.initialized=false;u.map={"page_type":"page_type","customer_uuid":"customer_uuid","product_id":"product_id","product_sku":"product_sku","product_quantity":"product_quantity","product_net_demand":"product_net_demand","product_gross_retail":"product_gross_retail","currency_code":"currency","order_id":"order_id","order_net_demand":"order_net_demand","order_tax":"order_tax","order_shipping":"order_shipping","order_total":"order_total","product_name":"product_name","product_category":"product_category","product_brand":"product_brand","granify_id":"account_id","product_gross_merchandise_bag":"product_gross_merchandise","product_markdown_amount":"product_markdown_amount"};u.extend=[];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={"account_id":"","base_url":"//cdn.granify.com/assets/javascript.js","event_types":["on","identify","addTag","trackPageView","trackProduct","trackCart","addToCart","deleteFromCart","trackOrder","setCurrentProduct"],"gr_page_type":"","items":[],"page_type":""
};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
function activateGranify(sid){if(!window.Granify)!function(r,t,e){var a,n;try{var i=window.localStorage,o="granify.entry_page."+t,c="granify.entry_referrer."+t;if(n=JSON.parse(i.getItem(o)),n&&parseInt(n.expires)>+new Date?n=n.data:(n=null,i.removeItem(o)),!n){i.removeItem(c),i.removeItem("granify.entry_page_sent."+t),i.removeItem("granify.entry_referrer_sent."+t);var s=window.location,f=window.location.origin;a=new Date(+new Date+18e5),f||(s.port?port=":"+s.port:port="",f=s.protocol+"//"+s.hostname+port);var y={data:window.location.toString().replace(f,""),expires:+a},p={data:document.referrer,expires:+a};i.setItem(o,JSON.stringify(y)),i.setItem(c,JSON.stringify(p))}}catch(r){}r=r+(-1===r.indexOf("?")?"?":"&")+"id="+t,window.Granify=function(r,t){Granify._functionsAvailable?Granify[r].apply(this,Array.prototype.slice.call(arguments,1)):Granify._stack.push([r].concat(Array.prototype.slice.call(arguments,1)))},Granify._stack=[],Granify._stack.push(["on","granify:init",function(){Granify._functionsAvailable=!0}]),Granify.init=function(r,t,e){for(var a=Granify,n=["on","identify","addTag","trackPageView","trackProduct","trackCart","addToCart","deleteFromCart","trackOrder","setCurrentProduct"],i=0;i<n.length;i++)!function(r,t){r[t]=function(){Granify._stack.push([t].concat(Array.prototype.slice.call(arguments,0)))}}(a,n[i])},Granify.init();}("",sid);}
activateGranify(u.data.account_id);u.loader_cb=function(){u.initialized=true;if(b.tealium_environment=='dev'||b.tealium_environment=='qa'){Granify('setDebugLogging',true);}
Granify('setShopperId',u.data.customer_uuid);if(u.data.page_type=='OrderConfirmation'){u.data.gr_page_type='receipt';u.data.items=[];if(u.data.product_id){for(var i=0;i<u.data.product_id.length;i++){if(window.location.pathname.indexOf('orderConfirm.do')!=-1){var item={sku:u.data.product_sku[i],product_id:u.data.product_id[i],quantity:u.data.product_quantity[i],price:u.data.product_net_demand[i],regular_price:u.data.product_gross_retail[i],product_brand:u.data.product_brand[i]};}else{var item={sku:u.data.product_sku[i],product_id:u.data.product_id[i],quantity:u.data.product_quantity[i],price:u.data.product_net_demand[i],regular_price:u.data.product_gross_retail[i],title:u.data.product_name[i],product_brand:u.data.product_brand[i]};}
u.data.items.push(item);}}
Granify('trackOrder',{currency:u.data.currency,order_number:u.data.order_id,total_line_items_price:u.data.order_net_demand,subtotal_price:u.data.order_net_demand,total_tax:u.data.order_tax,total_shipping:u.data.order_shipping,total_price:u.data.order_total,financial_status:'paid',line_items:u.data.items,discount_codes:[]});}else if(u.data.page_type=='ShoppingBag'||u.data.page_type=='InlinebagAdd'||u.data.page_type=='QuickAdd'){u.data.gr_page_type='cart';u.data.items=[];if(u.data.product_id){for(var i=0;i<u.data.product_id.length;i++){var item={sku:u.data.product_sku[i],product_id:u.data.product_id[i],quantity:u.data.product_quantity[i],price:u.data.product_gross_retail[i],regular_price:u.data.product_gross_retail[i],title:u.data.product_name[i]};u.data.items.push(item);}
Granify('trackCart',{items:u.data.items});}}else if(u.data.page_type=='Product'){u.data.gr_page_type='product';Granify('trackProduct',[{sku:u.data.product_sku,product_id:u.data.product_id,title:u.data.product_name,price:u.data.product_gross_retail,regular_price:u.data.product_gross_retail,in_stock:1,category:u.data.product_category}]);Granify('setCurrentProduct',{sku:u.data.product_sku,product_id:u.data.product_id});}else if(u.data.page_type=='Search'){u.data.gr_page_type='search';}else if(u.data.page_type=='Home'){u.data.gr_page_type='home';}else if(u.data.page_type=='Category'){u.data.gr_page_type='collection';}else{u.data.gr_page_type='other';}
Granify('trackPageView',u.data.gr_page_type);};if(!u.initialized){u.loader({"type":"script","src":u.data.base_url+'?id='+u.data.account_id,"cb":u.loader_cb,"loc":"script","id":'utag_1004'});}else{u.loader_cb();}
}};utag.o[loader].loader.LOAD(id);})("1004","gapinc.usgap");}catch(error){utag.DB(error);}
