//tealium universal tag - utag.1238 ut4.0.202604090403, Copyright 2026 Tealium.com Inc. All Rights Reserved.
if(!window.amzn){window.amzn=function(){window.amzn.q.push([arguments,(new Date).getTime()])};window.amzn.q=[];}
var amzn=window.amzn;try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={view:1,link:1};u.initialized=false;u.map={"cp.utag_main__ss":"sessionStart","page_type":"pageType","amzn_id":"account_id","order_id":"order_id","product_primary_category":"productCategory","tealium_random":"event_id,clientDedupeId"};u.extend=[];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={base_url:'https://c.amazon-adsystem.com/aat/amzn.js',region:'NA',account_id:'',order_id:'',event_id:'',clientDedupeId:'',event_queue:["PageView"],custom:{}};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
u.loader_cb=function(){u.initialized=true;amzn("setRegion",u.data.region);amzn("addTag",u.data.account_id);var setTealData={};if(u.data.order_id){setTealData.eventName="orderconfirmation";setTealData.order_id=u.data.order_id;u.data.event_queue.push('Purchase');}
if(u.data.sessionStart){setTealData.sessionStart=u.data.sessionStart;}
if(u.data.productCategory){setTealData.productCategory=u.data.productCategory;}
if(u.data.pageType){setTealData.pageType=u.data.pageType;}
if(u.data.clientDedupeId){setTealData.clientDedupeId=u.data.clientDedupeId;}
if(u.data.event_id){setTealData.event_id=u.data.event_id;}
if(u.data.event_queue.length>0){u.data.event_queue.forEach(function(event_name){amzn("trackEvent",event_name,setTealData);});}
};if(!u.initialized){u.loader({"type":"script","src":u.data.base_url,"cb":u.loader_cb,"loc":"script","id":'utag_1238'});}else{u.loader_cb();}
}};utag.o[loader].loader.LOAD(id);})("1238","gapinc.usgap");}catch(error){utag.DB(error);}
