//tealium universal tag - utag.2 ut4.0.202604090403, Copyright 2026 Tealium.com Inc. All Rights Reserved.
if(typeof JSON!=='object'){JSON={};}
(function(){'use strict';var rx_one=/^[\],:{}\s]*$/,rx_two=/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,rx_three=/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,rx_four=/(?:^|:|,)(?:\s*\[)+/g,rx_escapable=/[\\\"\u0000-\u001f\u007f-\u009f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,rx_dangerous=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g;function f(n){return n<10?'0'+n:n;}
function this_value(){return this.valueOf();}
if(typeof Date.prototype.toJSON!=='function'){Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+'-'+
f(this.getUTCMonth()+1)+'-'+f(this.getUTCDate())+'T'+f(this.getUTCHours())+':'+f(this.getUTCMinutes())+':'+
f(this.getUTCSeconds())+'Z':null;};Boolean.prototype.toJSON=this_value;Number.prototype.toJSON=this_value;String.prototype.toJSON=this_value;}
var gap,indent,meta,rep;function quote(string){rx_escapable.lastIndex=0;return rx_escapable.test(string)?'"'+string.replace(rx_escapable,function(a){var c=meta[a];return typeof c==='string'?c:'\\u'+('0000'+a.charCodeAt(0).toString(16)).slice(-4);})+'"':'"'+string+'"';}
function str(key,holder){var i,k,v,length,mind=gap,partial,value=holder[key];if(value&&typeof value==='object'&&typeof value.toJSON==='function'){value=value.toJSON(key);}
if(typeof rep==='function'){value=rep.call(holder,key,value);}
switch(typeof value){case'string':return quote(value);case'number':return isFinite(value)?String(value):'null';case'boolean':case'null':return String(value);case'object':if(!value){return'null';}
gap+=indent;partial=[];if(Object.prototype.toString.apply(value)==='[object Array]'){length=value.length;for(i=0;i<length;i+=1){partial[i]=str(i,value)||'null';}
v=partial.length===0?'[]':gap?'[\n'+gap+partial.join(',\n'+gap)+'\n'+mind+']':'['+partial.join(',')+']';gap=mind;return v;}
if(rep&&typeof rep==='object'){length=rep.length;for(i=0;i<length;i+=1){if(typeof rep[i]==='string'){k=rep[i];v=str(k,value);if(v){partial.push(quote(k)+(gap?': ':':')+v);}}}}else{for(k in value){if(Object.prototype.hasOwnProperty.call(value,k)){v=str(k,value);if(v){partial.push(quote(k)+(gap?': ':':')+v);}}}}
v=partial.length===0?'{}':gap?'{\n'+gap+partial.join(',\n'+gap)+'\n'+mind+'}':'{'+partial.join(',')+'}';gap=mind;return v;}}
if(typeof JSON.stringify!=='function'){meta={'\b':'\\b','\t':'\\t','\n':'\\n','\f':'\\f','\r':'\\r','"':'\\"','\\':'\\\\'};JSON.stringify=function(value,replacer,space){var i;gap='';indent='';if(typeof space==='number'){for(i=0;i<space;i+=1){indent+=' ';}}else if(typeof space==='string'){indent=space;}
rep=replacer;if(replacer&&typeof replacer!=='function'&&(typeof replacer!=='object'||typeof replacer.length!=='number')){throw new Error('JSON.stringify');}
return str('',{'':value});};}}());try{(function(id,loader,u){try{u=utag.o[loader].sender[id]={"id":id};}catch(e){u=utag.sender[id];}
utag.globals=window.utag.globals||{};u.toBoolean=function(val){val=String(val)||"";return val===true||val.toLowerCase()==="true"||val.toLowerCase()==="on";};u.ev={"all":1};u.do_enrichment=function(){};u.deepCopy=function(input){var key,copy;if(typeof input==="object"&&input!==null){if(utag.ut.typeOf(input)==="array"){copy=[];}else{copy={};}
for(key in input){if(typeof input[key]==="object"){copy[key]=u.deepCopy(input[key]);}else{copy[key]=input[key];}}}else{copy=input;}
return copy;}
u.get_account_profile=function(s){var p;if(u.visitor_service_override||u.tag_config_server.indexOf("tealiumiq.com")===-1){p=[u.tag_config_server.split("//")[1],u.account,u.profile]}else if(u.tag_config_server===u.event_url){p=[s.substring(s.indexOf(u.server_domain)).split("/")[1],u.account,u.profile]}else{p=s.substring(s.indexOf(u.server_domain)).split("/");}
return p;};function infixParameters(url,params){var updated_url,url_parts=url.split("?");if(params){if(url_parts[1]===undefined){updated_url=url+"?"+params;}else if(url_parts[1]===""){updated_url=url+params;}else{updated_url=url_parts[0]+"?"+params+"&"+url_parts[1];}}else{updated_url=url;}
return updated_url;}
u.is_in_sample_group=function(b){var group="100";if(u.tag_config_sampling===""||u.tag_config_sampling==="100"){return true;}
if(b["cp.utag_main_dc_group"]){group=b["cp.utag_main_dc_group"];}else{group=Math.floor(Math.random()*100)+1;utag.loader.SC("utag_main",{"dc_group":group});}
if(parseInt(group)<=parseInt(u.tag_config_sampling)){return true;}else{return false;}};u.get_performance_timing=function(b){var t,timing;var data={};function subtract(val1,val2){var difference=0;if(val1>val2){difference=val1-val2;}
return difference;}
try{timing=localStorage.getItem("tealium_timing");t=window.performance.timing;if(timing!==null&&timing!=="{}"&&typeof b!=="undefined"&&u.performance_timing_count===0){utag.ut.merge(b,utag.ut.flatten({timing:JSON.parse(timing)}),1);}}catch(e){utag.DB(e);return;}
u.performance_timing_count++;for(var k in t){if((k.indexOf("dom")===0||k.indexOf("load")===0)&&t[k]===0&&u.performance_timing_count<20){setTimeout(u.get_performance_timing,1000);}}
data["domain"]=location.hostname+"";data["pathname"]=location.pathname+"";data["query_string"]=(""+location.search).substring(1);data["timestamp"]=(new Date()).getTime();data["dns"]=subtract(t.domainLookupEnd,t.domainLookupStart);data["connect"]=subtract(t.connectEnd,t.connectStart);data["response"]=subtract(t.responseEnd,t.responseStart);data["dom_loading_to_interactive"]=subtract(t.domInteractive,t.domLoading);data["dom_interactive_to_complete"]=subtract(t.domComplete,t.domInteractive);data["load"]=subtract(t.loadEventEnd,t.loadEventStart);data["time_to_first_byte"]=subtract(t.responseStart,t.connectEnd);data["front_end"]=subtract(t.loadEventStart,t.responseEnd);data["fetch_to_response"]=subtract(t.responseStart,t.fetchStart);data["fetch_to_complete"]=subtract(t.domComplete,t.fetchStart);data["fetch_to_interactive"]=subtract(t.domInteractive,t.fetchStart);try{localStorage.setItem("tealium_timing",JSON.stringify(data));}catch(e){utag.DB(e);}};u.validateProtocol=function(address,force_ssl){if(/^https?:\/\//i.test(address)){if(force_ssl){if(/^http:\/\//i.test(address)){address=address.toLowerCase().replace("http","https");}}}else{if(/^\/\//.test(address)){if(force_ssl){address="https:"+address;}else{address=location.protocol+address;}
}else{if(force_ssl){address="https://"+address;}else{address=location.protocol+"//"+address;}}}
return address;}
u.server_domain="tealiumiq.com";u.server_prefix="";u.tag_config_server="";u.tag_config_sampling="100"||"100";if(utag.cfg.utagdb){u.tag_config_sampling="100";}
u.tag_config_region="us-west-2"||"default";u.region="";u.performance_timing_count=0;u.event_url='//collect.tealiumiq.com/event';u.account=utag.cfg.utid.split("/")[0];u.data_source="bo81hf";u.profile="main"||utag.cfg.utid.split("/")[1];u.visitor_service_override='visitor-service-us-west-2.tealiumiq.com';u.request_increment=1;u.iab_v20_compliance=true;u.tc_string="";u.use_sendBeacon='false';u.use_event_endpoint='true';u.tealium_cookie_domain='';u.tealium_cookie_expiry='';u.data_enrichment="frequent";u.send_udo_variables="true"||true;u.send_dom_values="true"||true;u.send_cookie_values="true"||true;u.send_meta_values="true"||true;u.send_query_param_values="true"||true;u.send_localstorage_variables="false"||false;u.send_sessionstorage_variables="false"||false;u.profile_specific_vid=0;u.enrichment_polling=1;u.enrichment_polling_delay=500;u.enrichment_enabled={};u.visitor_id="";u.suppress_v_id_generation="false"||false;u.map={};u.extend=[function(a,b){try{if(1){var time=Date.now();if(b['ut.event']==="view"){window.tealTimingCJA.collect=time;}
if(window.tealTimingCJA.adobe){var adobeTime=window.tealTimingCJA.adobe;var collectTime=window.tealTimingCJA.collect;if(!isNaN(adobeTime)&&!isNaN(collectTime)){var diff=collectTime-adobeTime;window.tealTimingCJA.diff=diff;b.analytics_timing_diff=diff;}}
b.customer_uuid=b.customer_uuid==='unknown'?null:b.customer_uuid;if(typeof utag.ut!=='undefined'){utag.ut.clear_collect=(list)=>{for(i in list){let cookie_var=list[i];b['cp.'+cookie_var]=undefined;}}
utag.ut.clear_collect(utag.ut.clear_cookie_list);}
if(b.fs_session_id&&b.fs_session_id!=='undefined'){b.tealium_fs_session_id=b.fs_session_id;}}}catch(e){utag.DB(e)}},function(a,b){try{if(b['ut.event'].toString().toLowerCase()=='view'.toLowerCase()){try{if(typeof utag.timing=='undefined')
{return;}
if(!b.page_type||typeof utag.timing[b.page_type]=='undefined')
{return;}
if(typeof utag.timing['ut_timing_start']!='undefined')
{b.ut_timing_start=utag.timing['ut_timing_start'];}
if(typeof utag.timing[b.page_type]['ut_timing_v1_start']!='undefined')
{b.ut_timing_v1_start=utag.timing[b.page_type]['ut_timing_v1_start'];}
if(typeof utag.timing[b.page_type]['ut_timing_v1_end']!='undefined')
{b.ut_timing_v1_end=utag.timing[b.page_type]['ut_timing_v1_end'];}
if(typeof utag.timing[b.page_type]['ut_timing_v2_start']!='undefined')
{b.ut_timing_v2_start=utag.timing[b.page_type]['ut_timing_v2_start'];}
if(localStorage.getItem('utag_timingQueue')!=null){var timingQueue=JSON.parse(localStorage.getItem('utag_timingQueue'));if(timingQueue.length>0){var timingFull=timingQueue.shift();window.tealPreviousTiming=timingFull;localStorage.setItem('utag_timingQueue',JSON.stringify(timingQueue));if(typeof timingFull['ut_timing_start']!='undefined'){b.ut_timing_prev_start=timingFull.ut_timing_start;}
if(typeof timingFull['ut_timing_v1_start']!='undefined'){b.ut_timing_prev_v1_start=timingFull.ut_timing_v1_start;}
if(typeof timingFull['ut_timing_v1_end']!='undefined'){b.ut_timing_prev_v1_end=timingFull.ut_timing_v1_end;}
if(typeof timingFull['ut_timing_v2_start']!='undefined'){b.ut_timing_prev_v2_start=timingFull.ut_timing_v2_start;}
if(typeof timingFull['ut_timing_v2_end']!='undefined'){b.ut_timing_prev_v2_end=timingFull.ut_timing_v2_end;}
if(typeof timingFull['page_type']!='undefined'){b.ut_timing_prev_page_type=timingFull.page_type;}
if(typeof timingFull['url']!='undefined'){b.ut_timing_prev_url=timingFull.url;}}}}
catch(ex){utag.DB(ex)}}}catch(e){utag.DB(e)}},function(a,b){try{if(1){var consent=["analytics","big_data","monitoring","personalization","engagement","cdp"];var existing=b["consent_categories"];if(!Array.isArray(existing)){b["consent_categories"]=consent;}else if(existing.length!==15){var existingSet=new Set(existing);consent.forEach(function(category){if(!existingSet.has(category)){b["consent_categories"].push(category);}});}}}catch(e){utag.DB(e)}},function(a,b){try{if(1){f='gapinc_main';if(b['_t_visitor_id']){b['_t_visitor_id']=b['_t_visitor_id']+f;}
if(b['cp.utag_main_v_id']){b['as_original_vid']=b['cp.utag_main_v_id'];b['cp.utag_main_v_id']=b['cp.utag_main_v_id']+f;}
if(b['ut.visitor_id']){b['ut.visitor_id']=b['ut.visitor_id']+f;}
if(b['tealium_visitor_id']){b['tealium_visitor_id']=b['tealium_visitor_id']+f;}}}catch(e){utag.DB(e)}},function(a,b){try{if(typeof b['cp.utag_main_tapid_reset']=='undefined'||typeof b['cp.utag_main_tapid_reset']!='undefined'&&b['cp.utag_main_tapid_reset']==''){b["tealium_override_tapid"]=b['tealium_visitor_id'];}}catch(e){utag.DB(e)}},function(a,b){try{if(typeof b['cp.utag_main_tapid_reset']=='undefined'||typeof b['cp.utag_main_tapid_reset']!='undefined'&&b['cp.utag_main_tapid_reset']==''){utag.loader.SC('utag_main',{'tapid_reset':'true'+';exp-'+((new Date()).getTime()+(365*864e5))+'u'});b['cp.utag_main_tapid_reset']='true';}}catch(e){utag.DB(e);}},function(a,b){try{if(1){b.gtag_account_id="stop";b.gtag_activity_group="stop";b.gtag_activity_id="stop";b.gtag_counting_method="stop";b.gtag_event="stop";if(b.business_unit_id){let c=["standard","transactions","unique"];let e=["conversion","purchase"];let p=["Home","Division","Category","Product","ShoppingBag","Search","OrderConfirmation","MiniBag"];let m=b['minibag_type'];let cid=b['qp.cid'];let page=b['page_type'];let tag={};let pmg1='DC-6900831';let pmg2='DC-8030980';let phd='DC-10709046';let buid=parseInt(b.business_unit_id);switch(buid){case 1:let akqa='DC-1956281';tag={acct:[pmg1,pmg2,akqa],group:['gap_r0','usgap0','gapde0'],activity:['gap_r0','gap-u002','gapde0'],count:[c[0],c[0],c[2]],event:[e[0]]};var addSinglePHD=(activity_id)=>{tag.acct=tag.acct.concat([phd]);tag.group=tag.group.concat(['phdga0']);tag.activity=tag.activity.concat([activity_id]);tag.count=tag.count.concat([c[0]]);};if(page){if(page===p[0]||page===p[2]||page===p[3]||page===p[4]||page===p[5]||(page===p[8]&&m==='shoppingBag')){tag.acct=tag.acct.concat([pmg2,akqa,akqa]);tag.group=tag.group.concat(['usgap0','gapde0','gapde0']);tag.count=tag.count.concat([c[0],c[2],c[0]]);if(page===p[0]){tag.acct=tag.acct.concat([akqa,phd]);tag.group=tag.group.concat(['gapco366','phdga0']);tag.count=tag.count.concat([c[0],c[0]]);tag.activity=tag.activity.concat(['gap-u0','gapde00','gapde000','gapcu255','gapho0']);}else if(page===p[2]||page===p[5]){tag.activity=tag.activity.concat(['gap-u000','gapde00','gapde000']);if(page===p[2]){if(cid==="1151802"){addSinglePHD('gapgi00');}
if(cid==="11900"){addSinglePHD('angus0');}
if(cid==="1027221"){addSinglePHD('gapba0');}
if(cid==="5664"){addSinglePHD('women00');}
if(cid==="1189735"){addSinglePHD('gapal0');}}}else if(page===p[3]){tag.activity=tag.activity.concat(['gap-u001','gapde00','gapde000']);}else if(page===p[4]||(page===p[8]&&m==='shoppingBag')){tag.acct=tag.acct.concat([akqa,akqa]);tag.group=tag.group.concat(['gapco366','gapde0']);tag.activity=tag.activity.concat(['gap-u00','gapde00','gapde000','gapco303','gapde001']);tag.count=tag.count.concat([c[0],c[2]]);}}else if(page===p[1]){if(cid==="1182426"){addSinglePHD('gapte0');}}else if(page===p[6]){tag.acct=[pmg1,pmg2,akqa,akqa,akqa];tag.group=['gap_p0','usgap00','gapco366','gapco366','gapde0'];tag.activity=['gap_p0','gap-u0','gapco840','gapco087','gapde002'];tag.count=[c[1],c[1],c[1],c[1],c[1]];tag.event=[e[1]];}else if(cid==="1174646"){addSinglePHD('gapio0');}else if(cid==="1182991"){addSinglePHD('gapco0');}}
break;case 2:pmg2='DC-8121544';phd='DC-1528929';tag={acct:[pmg1,pmg2,phd,phd],group:['gap_r0','usgap0','brcom299','brcom299'],activity:['gap_r0','banan0','brbro937','brsal434'],count:[c[0],c[0],c[0],c[0]],event:[e[0]]}
if(page){if(page===p[0]||page===p[2]||page===p[3]){tag.acct=tag.acct.concat([pmg2,phd]);tag.group=tag.group.concat(['usgap0','brcom299']);tag.count=tag.count.concat([c[0],c[0]]);b.gtag_account_id=[pmg2,phd];b.gtag_activity_group=['usgap0','brcom299'];b.gtag_counting_method=['standard','standard'];if(page===p[0]){tag.activity=tag.activity.concat(['banan00','brows891']);}else if(page===p[2]){tag.activity=tag.activity.concat(['banan000','brows891']);}else if(page===p[3]){tag.activity=tag.activity.concat(['banan001','brows891']);}}else if(page===p[1]){tag.acct=tag.acct.concat([phd]);tag.group=tag.group.concat(['brcom299']);tag.activity=tag.activity.concat(['brows891']);tag.count=tag.count.concat([c[0]]);}else if(page==p[4]||(page===p[8]&&m==='shoppingBag')){tag.acct=tag.acct.concat([pmg2,phd]);tag.group=tag.group.concat(['usgap0','brcom299']);tag.activity=tag.activity.concat(['banan002','brcar279']);tag.count=tag.count.concat([c[0],c[2]]);}else if(page==p[6]){tag.acct=[pmg1,pmg2,phd];tag.group=['gap_p0','us_ga0','brcom299'];tag.activity=['gap_p0','banan0','brord742'];tag.count=[c[1],c[1],c[1]];tag.event=[e[1]];}}
break;case 3:pmg2='DC-8110008';phd='DC-1393326';tag={acct:[pmg1,pmg2,phd,phd],group:['gap_r0','usold0','conve759','conve759'],activity:['gap_r0','oldna001','oldna970','OldNa0'],count:[c[0],c[0],c[0],c[2]],event:[e[0]]}
if(page){if(page===p[0]||page===p[2]||page===p[3]||page===p[4]||(page===p[8]&&m==='shoppingBag')){tag.acct=tag.acct.concat([pmg2]);tag.group=tag.group.concat(['usold0']);tag.count=tag.count.concat([c[0]]);if(page===p[0]){tag.activity=tag.activity.concat(['oldna0']);}else if(page===p[2]){tag.activity=tag.activity.concat(['oldna00']);}else if(page===p[3]){tag.activity=tag.activity.concat(['oldna000']);}else if(page===p[4]||(page===p[8]&&m==='shoppingBag')){tag.acct=tag.acct.concat([phd]);tag.group=tag.group.concat(['conve759']);tag.count=tag.count.concat([c[2]]);tag.activity=tag.activity.concat(['oldna002','oldna919']);}}else if(page===p[6]){tag.acct=[pmg1,pmg2,phd,phd,phd];tag.group=['gap_p0','usold00','conve759','oldna0','conve759'];tag.activity=['gap_p0','oldna0','oldna914','oldna0','oldna970'];tag.count=[c[1],c[1],c[0],c[2],c[0]];tag.event=[e[1]];}else if(cid==="1095422"){tag.acct=tag.acct.concat([pmg2]);tag.group=tag.group.concat(['usold0']);tag.activity=tag.activity.concat(['oldna00q']);tag.count=tag.count.concat([c[0]]);}}
break;case 10:pmg2='DC-8114858';phd='DC-3785825';tag={acct:[pmg1,pmg2,phd],group:['gap_r0','usath0','athle049'],activity:['gap_r0','athle0','athle432'],count:[c[0],c[0],c[0]],event:[e[0]]}
if(page){if(page===p[0]||page===p[2]||page===p[3]||page===p[4]||(page===p[8]&&m==='shoppingBag')){tag.acct=tag.acct.concat([pmg2]);tag.group=tag.group.concat(['usath0']);tag.count=tag.count.concat([c[0]]);if(page===p[0]){tag.activity=tag.activity.concat(['athle001']);}else if(page===p[2]){tag.activity=tag.activity.concat(['athle000']);}else if(page===p[3]){tag.activity=tag.activity.concat(['athle002']);}else if(page===p[4]||(page===p[8]&&m==='shoppingBag')){tag.acct=tag.acct.concat([phd]);tag.group=tag.group.concat(['athle049']);tag.count=tag.count.concat([c[2]]);tag.activity=tag.activity.concat(['athle00','athle816']);}}else if(page===p[6]){tag.group=['gap_p0','usath000','athle049'];tag.activity=['gap_p0','athle0','athle483'];tag.count=[c[1],c[1],c[0]];tag.event=[e[1]];}}
break;}
b.gtag_account_id=tag.acct;b.gtag_activity_group=tag.group;b.gtag_activity_id=tag.activity;b.gtag_counting_method=tag.count;b.gtag_event=tag.event;}}}catch(e){utag.DB(e)}},function(a,b){try{if((typeof b['page_type']!='undefined'&&b['page_type'].toString().toLowerCase().indexOf('division'.toLowerCase())>-1)){try{b['division']=b.channel.split(":")[1];}catch(e){}}}catch(e){utag.DB(e);}},function(a,b){try{if((typeof b['event_name']!='undefined'&&b['event_name'].toString().toLowerCase().indexOf('cart_add'.toLowerCase())>-1&&typeof b['product_brand']!='undefined'&&b['product_brand'].toString().toLowerCase().indexOf('gp'.toLowerCase())>-1)){try{b['product_brand']=["GAP"]}catch(e){}}}catch(e){utag.DB(e);}},function(a,b){try{if((typeof b['business_unit_id']!='undefined'&&typeof b['is_react']!='undefined')){b['certona_domain']='www.gap.com'}}catch(e){utag.DB(e);}},function(a,b){try{if(1){b['full_page_url']=b['dom.url']}}catch(e){utag.DB(e);}},function(a,b){try{if(typeof b['va.properties.5681']!='undefined'&&b['va.properties.5681']!=''){try{b['five_digit_zip']=b['va.properties.5681'].substring(0,5)}catch(e){}}}catch(e){utag.DB(e);}},function(a,b){try{if(1){function sanitizeABList1String(string){var result=string.replace(/[^,A-Z0-9:()]/ig,"_");return result;}
var ab_list=optimizely.get("custom/adobeIntegrator").campaignArray;if(typeof ab_list!="undefined"){b.ab_test_list=[];for(var i=ab_list.length-1;i>=0;i--){var campaignString=sanitizeABList1String(ab_list[i]);b.ab_test_list.push(campaignString);}}else{b.ab_test_list="optly_not_loaded";}
if(b.ab_test_list.length==0&&s.list1.length>0){b.ab_test_list=s.list1;}else if(b.ab_test_list.length==0){b.ab_test_list="";}}}catch(e){utag.DB(e)}},function(a,b){try{if((typeof b['cp.login_tracked']=='undefined'&&b['dom.referrer'].toString().toLowerCase().indexOf('/my-account/sign-in'.toLowerCase())>-1&&typeof b['qp.login']!='undefined'&&b['qp.login']!=''&&b['qp.login'].toString().toLowerCase().indexOf('success'.toLowerCase())>-1)){b['login_event']='login_success'}}catch(e){utag.DB(e);}},function(a,b){try{if((typeof b['cp.login_tracked']=='undefined'&&b['dom.referrer'].toString().toLowerCase().indexOf('/my-account/sign-in'.toLowerCase())>-1&&typeof b['qp.create_account']!='undefined'&&b['qp.create_account']!=''&&b['qp.create_account'].toString().toLowerCase().indexOf('success'.toLowerCase())>-1)){b['login_event']='create_account_success'}}catch(e){utag.DB(e);}},function(a,b){try{if((b['dom.referrer'].toString().toLowerCase().indexOf('/my-account/sign-in'.toLowerCase())>-1&&typeof b['qp.login']!='undefined'&&b['qp.login']!=''&&b['qp.login'].toString().toLowerCase().indexOf('success'.toLowerCase())>-1)||(b['dom.referrer'].toString().toLowerCase().indexOf('/my-account/sign-in'.toLowerCase())>-1&&typeof b['qp.create_account']!='undefined'&&b['qp.create_account']!=''&&b['qp.create_account'].toString().toLowerCase().indexOf('success'.toLowerCase())>-1)){document.cookie="login_tracked="+'true'+";path=/;domain="+utag.cfg.domain+";expires=";b['cp.login_tracked']='true';}}catch(e){utag.DB(e);}}];u.send=function(a,b){var c,d,i;if(u.ev[a]||typeof u.ev["all"]!=="undefined"){if(a==="remote_api"){utag.DB("Remote API event suppressed.");return;}
if(a==='update_consent_cookie'){utag.DB('Update Consent Cookie event supressed.');return;}
if(!u.toBoolean(u.suppress_v_id_generation)){u.visitor_id=u.visitor_id||b.tealium_visitor_id||b["cp.utag_main_v_id"];if(!u.visitor_id){var consentCookies=utag.gdpr&&typeof utag.gdpr.getCookieValues==='function'&&utag.gdpr.getCookieValues();var consentCookieId=consentCookies&&consentCookies.id;u.visitor_id=consentCookieId||utag.ut.vi((new Date()).getTime());utag.loader.SC("utag_main",{v_id:u.visitor_id});}
b["cp.utag_main_v_id"]=u.visitor_id;b["ut.visitor_id"]=u.visitor_id;b["tealium_visitor_id"]=u.visitor_id;}
try{if(utag.gdpr.consent_prompt.isEnabled||utag.gdpr.getConsentState()){b["consent_categories"]=utag.gdpr.getSelectedCategories();b["policy"]="gdpr";}}catch(e){utag.DB(e)}for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};utag.DB("send:2:EXTENSIONS");utag.DB(b);c=[];Object.keys(utag.loader.GV(u.map)).forEach(function(mapping_key){if(b[mapping_key]!==undefined&&b[mapping_key]!==''){var destinations=u.map[mapping_key].split(',');destinations.forEach(function(parameter){u[parameter]=b[mapping_key];});}});utag.DB("send:2:MAPPINGS");utag.DB(u);u.use_sendBeacon=u.toBoolean(u.use_sendBeacon);u.use_event_endpoint=u.toBoolean(u.use_event_endpoint);u.send_udo_variables=u.toBoolean(u.send_udo_variables);u.send_cookie_values=u.toBoolean(u.send_cookie_values);u.send_dom_values=u.toBoolean(u.send_dom_values);u.send_meta_values=u.toBoolean(u.send_meta_values);u.send_query_param_values=u.toBoolean(u.send_query_param_values);u.send_localstorage_variables=u.toBoolean(u.send_localstorage_variables);u.send_sessionstorage_variables=u.toBoolean(u.send_sessionstorage_variables);u.suppress_v_id_generation=u.toBoolean(u.suppress_v_id_generation);if(u.tag_config_server.indexOf("-collect."+u.server_domain)>1){u.server_prefix=u.tag_config_server.split("collect."+u.server_domain)[0];if(u.tag_config_server.indexOf("/i.gif")<0){u.tag_config_server="https://"+[u.server_prefix+"collect."+u.server_domain,u.account,u.profile,"2","i.gif"].join("/");}}
if(u.tag_config_server===""){if(u.use_event_endpoint){u.tag_config_server=u.event_url;}else if(u.tag_config_region==="default"){u.tag_config_server="https://"+[u.server_prefix+"collect."+u.server_domain,u.account,u.profile,"2","i.gif"].join("/");}else{u.tag_config_server="https://"+[u.server_prefix+"collect-"+u.tag_config_region+"."+u.server_domain,u.account,u.profile,"2","i.gif"].join("/");}}
if(u.tag_config_server.indexOf("-collect-")>-1){u.server_prefix=u.tag_config_server.split("collect-")[0];}
if(u.tag_config_region!=="default"&&u.tag_config_server.indexOf(u.server_prefix+"collect."+u.server_domain)>0){u.tag_config_server=u.tag_config_server.replace(u.server_prefix+"collect."+u.server_domain,u.server_prefix+"collect-"+u.tag_config_region+"."+u.server_domain);u.region=u.tag_config_region;}
var q=u.tag_config_server.indexOf("?");if(q>0&&(q+1)==u.tag_config_server.length){u.tag_config_server=u.tag_config_server.replace("?","");}
u.server_list=u.tag_config_server.split("|");if(u.tealium_cookie_domain){b.tealium_cookie_domain=u.tealium_cookie_domain;}
if(u.tealium_cookie_expiry){b.tealium_cookie_expiry=parseInt(u.tealium_cookie_expiry);}
if(u.iab_v20_compliance===true||u.iab_v20_compliance==="true"){if(typeof __tcfapi==="function"){__tcfapi("getTCData",2,function(tcData,success){if(success){u.tc_string="gdpr=";if(tcData.gdprApplies===true){u.tc_string+="1";}else if(tcData.gdprApplies===false){u.tc_string+="0";}else{u.tc_string+=String(tcData.gdprApplies);}
u.tc_string+="&gdpr_consent="+tcData.tcString;execute_send();}});}else{var frame=window;var cmpFrame;var cmpCallbacks={};while(frame){try{if(frame.frames["__tcfapiLocator"]){cmpFrame=frame;break;}}catch(error){utag.DB(error);}
if(frame===window.top){break;}
frame=frame.parent;}
if(!cmpFrame){execute_send();}else{window.__tcfapi=function(cmd,version,callback,arg){var callId=String(Math.random());var msg={__tcfapiCall:{command:cmd,parameter:arg,version:version,callId:callId}};cmpCallbacks[callId]=callback;cmpFrame.postMessage(msg,"*");};window.tealiumiabPostMessageHandler=function(event){var json={};try{json=typeof event.data==="string"?JSON.parse(event.data):event.data;}catch(error){utag.DB(error);}
var payload=json.__tcfapiReturn;if(payload){if(typeof cmpCallbacks[payload.callId]==="function"){cmpCallbacks[payload.callId](payload.returnValue,payload.success);cmpCallbacks[payload.callId]=null;}}};window.addEventListener("message",tealiumiabPostMessageHandler,false);__tcfapi("getTCData",2,function(tcData,success){if(success){u.tc_string="gdpr=";if(tcData.gdprApplies===true){u.tc_string+="1";}else if(tcData.gdprApplies===false){u.tc_string+="0";}else{u.tc_string+=String(tcData.gdprApplies);}
u.tc_string+="&gdpr_consent="+tcData.tcString;execute_send();}});}}}else{execute_send();}
function execute_send(){if(u.data_source){b.tealium_datasource=u.data_source;}
u.make_enrichment_request=false;if(!u.is_in_sample_group(b)){return false;}
u.get_performance_timing(b);for(i=0;i<u.server_list.length;i++){if(u.server_list[i].toLowerCase().indexOf("http")===-1){u.server_list[i]=u.validateProtocol(u.server_list[i],true);}
if(u.enrichment_enabled[i]!==false){u.enrichment_enabled[u.server_list[i]]=true;}}
if(u.server_list.length>1){u.profile_specific_vid=1;}
u.data=utag.datacloud||{};u.data["loader.cfg"]={};for(d in utag.loader.GV(utag.loader.cfg)){if(utag.loader.cfg[d].load&&utag.loader.cfg[d].send){utag.loader.cfg[d].executed=1;}else{utag.loader.cfg[d].executed=0;}
u.data["loader.cfg"][d]=utag.loader.GV(utag.loader.cfg[d]);}
u.data.data=b;for(d in u.data.data){if((d+'').indexOf("qp.")===0){u.data.data[d]=encodeURIComponent(u.data.data[d]);}else if((d+'').indexOf("va.")===0){delete u.data.data[d];}}
if(!b["cp.utag_main_dc_event"]){b["cp.utag_main_dc_visit"]=(1+(b["cp.utag_main_dc_visit"]?parseInt(b["cp.utag_main_dc_visit"]):0))+"";}
b["cp.utag_main_dc_event"]=(1+(b["cp.utag_main_dc_event"]?parseInt(b["cp.utag_main_dc_event"]):0))+"";utag.loader.SC("utag_main",{"dc_visit":b["cp.utag_main_dc_visit"],"dc_event":b["cp.utag_main_dc_event"]+";exp-session"});utag.data["cp.utag_main_dc_visit"]=b["cp.utag_main_dc_visit"];utag.data["cp.utag_main_dc_event"]=b["cp.utag_main_dc_event"];var dt=new Date();u.data.browser={};try{u.data.browser["height"]=window.innerHeight||document.body.clientHeight;u.data.browser["width"]=window.innerWidth||document.body.clientWidth;u.data.browser["screen_height"]=screen.height;u.data.browser["screen_width"]=screen.width;u.data.browser["timezone_offset"]=dt.getTimezoneOffset();}catch(e){utag.DB(e);}
u.data["event"]=a+'';u.data["post_time"]=dt.getTime();if(u.data_enrichment==="frequent"||u.data_enrichment==="infrequent"){u.visit_num=b["cp.utag_main_dc_visit"];if(parseInt(u.visit_num)>1&&b["cp.utag_main_dc_event"]==="1"){u.enrichment_polling=2;}
try{u.va_update=parseInt(localStorage.getItem("tealium_va_update")||0);}catch(e){utag.DB(e);}
u.visitor_id=u.visitor_id||b.tealium_visitor_id||b["cp.utag_main_v_id"];if(u.data_enrichment==="frequent"||(u.data_enrichment==="infrequent"&&parseInt(u.visit_num)>1&&parseInt(b["cp.utag_main_dc_event"])<=5&&u.visit_num!==u.va_update)){u.make_enrichment_request=true;}
u.visitor_service_request=function(t,server){var s,p=u.get_account_profile(server);if(u.visitor_service_override){s=u.validateProtocol(u.visitor_service_override,true);}else{s=u.validateProtocol(u.server_prefix,true)+"visitor-service"+(u.region?"-"+u.region:"").replace(/[^-A-Za-z0-9+_.]/g,"")+"."+u.server_domain;}
(function(p){var prefix="tealium_va";var key="_"+p[1]+"_"+p[2];utag.ut["writeva"+p[2]]=function(o){utag.DB("Visitor Attributes: "+prefix+key);utag.DB(o);var str=JSON.stringify(o);if(str!=="{}"&&str!==""){try{localStorage.setItem("tealium_va_update",utag.data["cp.utag_main_dc_visit"]);localStorage.setItem(prefix,str);localStorage.setItem(prefix+key,str);}catch(e){utag.DB(e);}
if(typeof tealium_enrichment==="function"){tealium_enrichment(o,prefix+key);}}};}(p.slice(0)));var vid=b.tealium_override_tapid||b.tealium_visitor_id||b['cp.utag_main_v_id']||u.visitor_id;if(u.profile_specific_vid===1){vid+=p[2];}
var srcUrl=s+'/'+p[1]+'/'+p[2]+'/'+vid.replace(/[\?\&]callback=.*/g,'')+'?callback=utag.ut%5B%22writeva'+p[2]+'%22%5D&rnd='+t;if(b.tealium_cookie_domain){srcUrl=srcUrl+'&tealium_cookie_domain='+b.tealium_cookie_domain
if(b.tealium_cookie_expiry){srcUrl=srcUrl+'&tealium_cookie_expiry='+b.tealium_cookie_expiry}}
utag.ut.loader({id:'tealium_visitor_service_2'+p[2]+'_'+u.request_increment++,src:srcUrl});};u.do_enrichment=function(server,enrichment_polling,enrichment_polling_delay){if(typeof utag.ut.loader!="undefined"){for(i=0;i<enrichment_polling;i++){setTimeout(function(){u.visitor_service_request((new Date).getTime(),server);},i*enrichment_polling_delay+1);}}};}
var json_string,regExpReplace=new RegExp(u.visitor_id,"g");if(b.tealium_random&&typeof utag.globals[b.tealium_random]==="object"){for(var downstream_param in utag.globals[b.tealium_random]){u.data.data[downstream_param]=u.deepCopy(utag.globals[b.tealium_random][downstream_param]);}}
function getSendData(useEventData,server){var dataStringify=u.data;var filterObject=u.data.data
if(useEventData){dataStringify=u.data.data;filterObject=u.data.data;u.data.data.tealium_profile=u.profile;}
Object.keys(filterObject).forEach(dataKey=>{if(['cp.trace_id','tealium_account','tealium_profile'].indexOf(dataKey)!==-1){return;}
if(dataKey.indexOf('cp.')===0){!u.send_cookie_values&&delete filterObject[dataKey];return;}
if(dataKey.indexOf('meta.')===0){!u.send_meta_values&&delete filterObject[dataKey];return;}
if(dataKey.indexOf('qp.')===0){!u.send_query_param_values&&delete filterObject[dataKey];return;}
if(dataKey.indexOf('ls.')===0){!u.send_localstorage_variables&&delete filterObject[dataKey];return;}
if(dataKey.indexOf('ss.')===0){!u.send_sessionstorage_variables&&delete filterObject[dataKey];return;}
if(dataKey.indexOf('dom.')===0){!u.send_dom_values&&delete filterObject[dataKey];return;}
if(dataKey.indexOf('dom.')!==0&&dataKey.indexOf('ss.')!==0&&dataKey.indexOf('ls.')!==0&&dataKey.indexOf('qp.')!==0&&dataKey.indexOf('meta.')!==0&&dataKey.indexOf('cp.')!==0){!u.send_udo_variables&&delete filterObject[dataKey];return;}});json_string=JSON.stringify(dataStringify);if(u.profile_specific_vid===1&&u.visitor_id){json_string=json_string.replace(regExpReplace,u.visitor_id+u.get_account_profile(server)[2]);}
if(useEventData){return json_string;}
var formData=new FormData();formData.append("data",json_string);return formData;}
function postData(server_index,enrichment_polling,enrichment_polling_delay,useEventData){if(server_index+1>u.server_list.length){return;}
var xhr=new XMLHttpRequest();var server=u.validateProtocol(u.server_list[server_index],true);var data=getSendData(useEventData,server);u.region=utag.loader.RC("utag_main")["dc_region"]||u.region||"";if(typeof navigator.sendBeacon==='function'&&u.region!==""&&u.use_sendBeacon){u.server_list.forEach(function(serverItem){var beaconSent=navigator.sendBeacon(infixParameters(serverItem,u.tc_string),data);if(!beaconSent){xhr.open("post",infixParameters(serverItem,u.tc_string),true);xhr.withCredentials=true;xhr.send(data);}
if(u.make_enrichment_request&&u.enrichment_enabled[serverItem]){u.do_enrichment(serverItem,enrichment_polling,enrichment_polling_delay);}});utag.DB("Data sent using sendBeacon");return;}
xhr.addEventListener("readystatechange",function(){if(xhr.readyState===3){try{u.region=xhr.getResponseHeader("X-Region")||u.region||"";}catch(res_error){utag.DB(res_error);u.region=u.region||"";}
if(u.region)utag.loader.SC("utag_main",{"dc_region":u.region+";exp-session"});utag.DB("dc_region:"+u.region);}else if(xhr.readyState===4){postData(server_index+1,enrichment_polling,enrichment_polling_delay,useEventData);if(u.make_enrichment_request&&u.enrichment_enabled[server]){u.do_enrichment(server,enrichment_polling,enrichment_polling_delay);}}});if(u.server_list[server_index].toLowerCase().indexOf("http")!==0){u.server_list[server_index]=u.validateProtocol(u.server_list[server_index],true);}
var serverUrl=infixParameters(u.server_list[server_index],u.tc_string);xhr.open("post",serverUrl,true);xhr.withCredentials=true;xhr.send(data);}
if(u.use_event_endpoint&&(u.tag_config_server===u.event_url||u.tag_config_region!=="default")&&window.FormData){postData(0,u.enrichment_polling,u.enrichment_polling_delay,true);}else if(window.FormData){postData(0,u.enrichment_polling,u.enrichment_polling_delay,false);}else{for(i=0;i<u.server_list.length;i++){(function(i,enrichment_polling,enrichment_polling_delay){var server=u.server_list[i];setTimeout(function(){json_string=JSON.stringify(u.data);if(u.profile_specific_vid==1&&u.visitor_id){json_string=json_string.replace(regExpReplace,u.visitor_id+u.get_account_profile(server)[2]);}
var img=new Image();img.src=server+"?"+(u.tc_string?u.tc_string+"&":"")+"data="+encodeURIComponent(json_string);if(u.make_enrichment_request&&u.enrichment_enabled[server]){u.do_enrichment(server,enrichment_polling,enrichment_polling_delay);}},i*700);}(i,u.enrichment_polling,u.enrichment_polling_delay));}}}}};try{utag.o[loader].loader.LOAD(id);}catch(e){utag.loader.LOAD(id);}})("2","gapinc.usgap");}catch(e){utag.DB(e);}
