//tealium universal tag - utag.709 ut4.0.202604090403, Copyright 2026 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={'view':1};u.initialized=false;u.map={"cp.s_vi":"AdobeSvi","cp.utag_main_ses_id":"tealiumSessionId","cp.utag_main_v_id":"tealiumVisitorId","tealium_timestamp_epoch":"orderTimestamp","country_code":"countryCode","user_agent":"userAgent","page_name":"tealiumPageName"};u.extend=[];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
(window["nr_object"]={"eventType":"VisitsTealium","AdobeSvi":u.data.AdobeSvi||'',tealiumSessionId:b["cp.utag_main_ses_id"],tealiumVisitorId:b["cp.utag_main_v_id"],tealiumIsFirstPageView:b["cp.utag_main__ss"],tealiumSessionPageCount:b["cp.utag_main__pn"],tealiumSessionCount:b["cp.utag_main__sn"],tealiumCustomerUUID:b["customer_uuid"],tealiumCardholderStatus:b["cardholder_status"],tealiumMtlMember:b["pas_MtlMember"],tealiumDivisionPreference:b["division_pref_Position1"],tealiumEvergreenSplit:b["evergreen_split"],tealiumPageType:b["page_type"],tealiumBrandName:b["brand_name"],tealiumEnvironment:b["tealium_environment"],tealiumProfile:b["tealium_profile"],tealiumCountryCode:b["country_code"],tealiumUnknownShopperId:b["unknown_shopper_id"],tealiumUserAgent:b["user_agent"],tealiumPageName:b["page_name"],tealiumIPhoneScreen:b["iphone_screen"],tealiumMobileVersion:b["mobile_version"]})
var xmlhttp=new XMLHttpRequest();if(b["ut.env"]=="prod")
{xmlhttp.open("POST","https://insights-collector.newrelic.com/v1/accounts/1334766/events");}
else
{xmlhttp.open("POST","https://insights-collector.newrelic.com/v1/accounts/1542405/events");}
xmlhttp.withCredentials=false;if(b["ut.env"]=="prod")
{xmlhttp.setRequestHeader("X-Insert-Key","ylppX1kwDJ1O_g_2xhAf8HyoNw_0G_iu");}
else
{xmlhttp.setRequestHeader("X-Insert-Key","oW9OrfZuAcNQq-13Zi4NKkhBFcsUwFal");}
xmlhttp.setRequestHeader("Content-Type","application/json;charset=UTF-8");xmlhttp.send(JSON.stringify(window["nr_object"]));}};utag.o[loader].loader.LOAD(id);})("709","gapinc.usgap");}catch(error){utag.DB(error);}
