//tealium universal tag - utag.36 ut4.0.202604070610, Copyright 2026 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}
if(utag.ut.loader===undefined){u.loader=function(o){var b,c,l,a=document;if(o.type==="iframe"){b=a.createElement("iframe");o.attrs=o.attrs||{"height":"1","width":"1","style":"display:none"};for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute("src",o.src);}else if(o.type=="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";for(l in utag.loader.GV(o.attrs)){b[l]=o.attrs[l];}b.src=o.src;}if(o.id){b.id=o.id};if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb()},false);}else{b.onreadystatechange=function(){if(this.readyState=='complete'||this.readyState=='loaded'){this.onreadystatechange=null;o.cb()}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b)}}}}else{u.loader=utag.ut.loader;}
u.ev={view:1,link:1};u.initialized=false;u.map={};u.extend=[function(a,b){try{if(1){var cart_object={id:tiq.tools.get_cookie("ecom_cart_id")||"",coupon:(b._cpromo[0]!=="")?b._cpromo[0]:undefined};if(typeof window.attentive==="undefined"||typeof window.attentive.analytics==="undefined"){return;}else{if(b.product_action==="detail"){window.attentive.analytics.productView({items:u.data.popProduct(),});}
if(b.product_action==="add"){window.attentive.analytics.addToCart({items:u.data.popProduct(),cart:cart_object});}
if(b.product_action==="purchase"){var order_object={orderId:b.order_id};window.attentive.analytics.purchase({items:u.data.popProduct(),cart:cart_object,order:order_object});}
if(a==="view"||(a==="link"&&b.product_action==="remove")){var current_cart=[];if(tiq.tools.variable_is(tiq.cartState)){for(var i=0;i<tiq.cartState.length;i++){var product={};product.productId=tiq.cartState[i].sku;product.quantity=tiq.cartState[i].quantity;product.price={};product.price.value=tealiumiq_currency.convert(tiq.cartState[i].priceEachAsNumber.toString(),b.region_currency,"EUR");product.price.currency=b._ccurrency;current_cart.push(product);}}
window.attentive.analytics.updateCart({items:current_cart,cart:cart_object});}}}}catch(e){utag.DB(e)}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={popProduct(){let c={};var f=[];for(var i=0;i<b._cprod.length;i++){var e={};e.productId=(b._cprod&&tiq.tools.variable_is(b._cprod[i]))?b._cprod[i]:undefined;e.productVariantId=(b.product_variant_id&&tiq.tools.variable_is(b.product_variant_id[i]))?b.product_variant_id[i]:undefined;e.name=(b._cprodname&&tiq.tools.variable_is(b._cprodname[i]))?b._cprodname[i].toLowerCase():undefined;e.category=(b._ccat&&tiq.tools.variable_is(b._ccat[i]))?b._ccat[i].toLowerCase():undefined;e.quantity=(b._cquan&&tiq.tools.variable_is(b._cquan[i]))?Number(b._cquan[i]):undefined;e.price={};e.price.value=(b._cprice&&tiq.tools.variable_is(b._cprice[i]))?Math.round(Number(b._cprice[i])*100)/100:undefined;e.price.currency=b._ccurrency;f.push(e);}
return f;}};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
}};utag.o[loader].loader.LOAD(id);})("36","hm.cosweb");}catch(error){utag.DB(error);}
