//tealium universal tag - utag.16 ut4.0.202604070610, Copyright 2026 Tealium.com Inc. All Rights Reserved.
var ScarabQueue=ScarabQueue||[];try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={"view":1,"link":1};u.initialized=false;u.typeOf=function(e){return({}).toString.call(e).match(/\s([a-zA-Z]+)/)[1].toLowerCase();};u.map={"customer_bpid_output":"customer_id","page_type":"page_type","em_merchant_id":"merchant_id","search_term":"searchTerm"};u.extend=[function(a,b){try{if(1){if(b.region_market==="us"||b.region_market==="ca"){b.em_merchant_id="1A8131F4B952E18F";if(b["ut.env"]==="prod"){b.em_merchant_id="18D72F72B2C9DDF8";}}else{b.em_merchant_id="15E34795EED32B99";if(b["ut.env"]==="prod"){b.em_merchant_id="1FEA42A80FAD3774";}}
if(b.product_action==="purchase"){b._cprod=b.product_variant_id;}
if(a==="view"||(a==="link"&&b.product_action==="remove")){var current_cart=[];if(tiq.tools.variable_is(tiq.cartState)){for(var i=0;i<tiq.cartState.length;i++){var product={};product.item=tiq.cartState[i].sku;product.quantity=tiq.cartState[i].quantity;var price=tealiumiq_currency.convert(tiq.cartState[i].priceEachAsNumber.toString(),b.region_currency,"EUR");product.price=parseFloat(price)*tiq.cartState[i].quantity;current_cart.push(product);}}
ScarabQueue.push(["cart",current_cart]);if(b.page_is_productList===1){if(tiq.tools.variable_is(b.attraqt_source_category)){var category=b.attraqt_source_category;category=category.replace(/_/g,">");ScarabQueue.push(["category",category]);}}}
if(tiq.tools.variable_is(b.product_price)){var prices=[];for(let i=0;i<b.product_price.length;i++){var price=tealiumiq_currency.convert(b.product_price[0],b.region_currency,"EUR");prices.push(parseFloat(price));}
b._cprice=prices;}
if(b.product_action==="detail"){b.page_type="product";for(var i=0;i<b.product_article_id.length;i++){b._cprod[i]="g/"+b.product_article_id[i];}}}}catch(e){utag.DB(e)}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f;u.data={"base_url":('https:'==document.location.protocol?'https://recommender':'http://cdn')+'.scarabresearch.com/js/@@MERCHANT_ID@@/scarab-v2.js',"merchant_id":"","script_id":"scarab-js-api","page_type":"other","availabilityZone":"","keywords":[],"searchTerm":"","rec_logic":"","rec_con_id":"","rec_temp_id":"","rec_limit":"","rec_baseline":"","rec_success_cb":"","restriction":[],"r_map":{'ex':"exclude",'in':"include"},"order_id":"","customer_id":"","customer_email":"","product_id":[],"product_category":[],"product_quantity":[],"product_unit_price":[]};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};c=[];for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){if(/^(ex|in)_/.test(e[f])){var m=e[f].split('_');u.data.restriction.push({'t':m[0],'f':m[1],'c':m[2],'v':b[d]});}else{u.data[e[f]]=b[d];}}}}
u.data.base_url=u.data.base_url.replace('@@MERCHANT_ID@@',u.data.merchant_id);u.data.order_id=u.data.order_id||b._corder||"";u.data.customer_id=u.data.customer_id||b._ccustid||"";if(u.data.product_id.length===0&&b._cprod!==undefined){u.data.product_id=b._cprod.slice(0);}
if(u.data.product_category.length===0&&b._ccat!==undefined){u.data.product_category=b._ccat.slice(0);}
if(u.data.product_quantity.length===0&&b._cquan!==undefined){u.data.product_quantity=b._cquan.slice(0);}
if(u.data.product_unit_price.length===0&&b._cprice!==undefined){u.data.product_unit_price=b._cprice.slice(0);}
u.loader_cb=function(){u.initialized=true;if(u.typeOf(u.data.keywords)==="string"){ScarabQueue.push(['addKeyword',u.data.keywords]);}else if(u.typeOf(u.data.keywords)==="array"){for(var i=0;i<u.data.keywords.length;i++){ScarabQueue.push(['addKeyword',u.data.keywords[i]]);}}
if(u.data.availabilityZone){ScarabQueue.push(['availabilityZone',u.data.availabilityZone]);}
if(u.data.page_type=="cart"||u.data.order_id){var prods=[];for(var i=0;i<u.data.product_id.length;i++){prods.push({'item':u.data.product_id[i],'price':u.data.product_unit_price[i],'quantity':u.data.product_quantity[i]});}}
if(u.data.order_id){ScarabQueue.push(['purchase',{orderId:u.data.order_id,items:prods}]);ScarabQueue.push(["cart",[]]);}else if(u.data.page_type=="cart"){ScarabQueue.push(['cart',prods]);}
if(u.data.page_type==="product"){if(u.data.product_id[0]){ScarabQueue.push(['view',u.data.product_id[0]]);}}
for(var i=0;i<u.data.restriction.length;i++){var item=u.data.restriction[i];ScarabQueue.push([u.data.r_map[item.t],item.f,item.c,item.v]);}
if(u.data.rec_logic&&u.data.rec_con_id){if(u.typeOf(u.data.rec_baseline)!=="array"){u.data.rec_baseline=[u.data.rec_baseline];}
ScarabQueue.push(['recommend',{logic:u.data.rec_logic,containerId:u.data.rec_con_id,templateId:u.data.rec_temp_id,limit:(parseInt(u.data.rec_limit)||5),baseline:u.data.rec_baseline,success:function(SC,render){if(u.typeOf(window[u.data.rec_success_cb])==="function"){window[u.data.rec_success_cb](SC);}
render(SC);}}]);}
if(u.data.searchTerm){ScarabQueue.push(['searchTerm',u.data.searchTerm]);}
if(u.data.customer_id){ScarabQueue.push(['setCustomerId',u.data.customer_id]);}
if(u.data.customer_email){ScarabQueue.push(['setEmail',u.data.customer_email]);}
ScarabQueue.push(['go']);};if(!u.initialized){u.loader({"type":"script","src":u.data.base_url,"cb":u.loader_cb,"loc":"script","id":u.data.script_id});}else{u.loader_cb();}
}};utag.o[loader].loader.LOAD(id);}("16","hm.cosweb"));}catch(error){utag.DB(error);}
