#!/usr/bin/env tsx
/**
 * Generates extension/registry.js from SITE_REGISTRY.
 *
 * Run automatically as part of `npm run build:ext`.
 * The output is a plain JS file (no modules) that extension/background.js
 * loads via importScripts(), providing REGISTRY_HOSTNAMES as a global.
 */

import { writeFileSync } from "fs";
import { SITE_REGISTRY } from "../src/registry/sites.js";

const hostnames = SITE_REGISTRY.map((c) => c.hostname);

const content =
  `// AUTO-GENERATED by npm run build:registry — do not edit manually.\n` +
  `// Source of truth: src/registry/sites.ts\n` +
  `// Rebuild with: npm run build:ext\n` +
  `const REGISTRY_HOSTNAMES = ${JSON.stringify(hostnames)};\n`;

writeFileSync("extension/registry.js", content);
console.log(
  `Generated extension/registry.js with ${hostnames.length} registry entr${hostnames.length === 1 ? "y" : "ies"}: ${hostnames.join(", ") || "(none)"}`
);
